GET {{baseUrl}}/book HTTP/1.1
Content-Type: application/json
token: {{token}}

###

GET {{baseUrl}}/book/1 HTTP/1.1
Content-Type: application/json
token: {{token}}

###

POST {{baseUrl}}/book HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "BookName": "mert",
    "BookPageCount": 100,
    "BookType":"seri",
    "AuthorId": 2
}

###

PUT {{baseUrl}}/book HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "Id": 2,
    "BookName": "mert",
    "BookPageCount": 1001,
    "BookType":"seri",
    "AuthorId": 2
}

###

DELETE  {{baseUrl}}/book HTTP/1.1
Content-Type: application/json
token: {{token}}

{
    "Id": 1
}